### ISSUE TITLE
Prioritize issue types

### ISSUE THREAD

**Issue by hielfx** [InditexTech/gh-sherpa#21]
### Motivation

Currently we don't have a to prioritize GH Sherpa issue types.

In case an issue has several labels associated to several issue types, there should be a way to prioritize one issue type over the others.

One way to achieve this could be creating a new configuration (or inside the current `branches` one) so we can provide a way to configure this priority, using (for example) a list:

```yaml
...
branches:
  issue_types_priority: ["bugfix", "feature", "refactoring", "documentation", ...]
```

### Acceptance criteria

- [ ] A check list of tasks to be done to assume the issue addressed
